### ISSUE TITLE
1.13.2 on startup error

### ISSUE THREAD

**Issue by BaxAndrei** [MegaNarwhal/BiomeFinder#5]
```[18:52:10] [Server thread/ERROR]: Error occurred while enabling BiomeFinder v1.2.9 (Is it up to date?)
java.lang.NoSuchFieldError: MUTATED_PLAINS
	at us.blockbox.biomefinder.command.CommandBfTp.getGuiStacks(CommandBfTp.java:153) ~[?:?]
	at us.blockbox.biomefinder.command.CommandBfTp.<init>(CommandBfTp.java:38) ~[?:?]
	at us.blockbox.biomefinder.BiomeFinder.setupCommands(BiomeFinder.java:113) ~[?:?]
	at us.blockbox.biomefinder.BiomeFinder.onEnable(BiomeFinder.java:79) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [server.jar:git-Spigot-a1f2566-97b0057]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [server.jar:git-Spigot-a1f2566-97b0057]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [server.jar:git-Spigot-a1f2566-97b0057]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [server.jar:git-Spigot-a1f2566-97b0057]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [server.jar:git-Spigot-a1f2566-97b0057]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [server.jar:git-Spigot-a1f2566-97b0057]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [server.jar:git-Spigot-a1f2566-97b0057]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [server.jar:git-Spigot-a1f2566-97b0057]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [server.jar:git-Spigot-a1f2566-97b0057]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]```

**Comment by colebob9** [comment]
I'm getting the same exact error on Paper 1.14.4 (#167), the error disables the plugin entirely.

**Comment by colebob9** [comment]
Turns out this error is related to UILib being installed, simply taking UILib out of the plugins folder fixes this. Obviously, this means you cannot use the GUI portion of this plugin.

**Comment by MegaNarwhal** [comment]
The GUI feature is no longer maintained and will be removed in a future release.
