### ISSUE TITLE
1.2.9 Startup Error

### ISSUE THREAD

**Issue by djodjo02130** [MegaNarwhal/BiomeFinder#8]
17:38:33 [FATAL] Could not load plugin
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchFieldError: STATIONARY_LAVA
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[?:?]
        at nl.rutgerkok.pokkit.plugin.PokkitPluginLoader.loadPlugin(PokkitPluginLoader.java:113) ~[?:?]
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:288) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at nl.rutgerkok.pokkit.plugin.PokkitPluginManager.loadPlugins(PokkitPluginManager.java:202) ~[?:?]
        at org.bukkit.craftbukkit.v1_99_R9.CraftServer.loadPlugins(CraftServer.java:715) ~[?:?]
        at nl.rutgerkok.pokkit.pluginservice.PluginService.onLoad(PluginService.java:36) ~[?:?]
        at nl.rutgerkok.pokkit.Pokkit.lambda$onLoad$2(Pokkit.java:120) ~[?:?]
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) [nukkit-1.0-SNAPSHOT.jar:?]
        at nl.rutgerkok.pokkit.Pokkit.onLoad(Pokkit.java:120) [Pokkit-0.8.jar:0.8]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
        at nl.rutgerkok.pokkit.startup.NukkitHook.onLoad(NukkitHook.java:40) [Pokkit-0.8.jar:0.8]
        at cn.nukkit.plugin.JavaPluginLoader.initPlugin(JavaPluginLoader.java:109) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:57) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:272) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:481) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NoSuchFieldError: STATIONARY_LAVA
        at us.blockbox.biomefinder.BiomeFinder.<clinit>(BiomeFinder.java:44) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_221]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[?:?]
        ... 24 more
17:38:33 [FATAL] Could not load plugin "BiomeFinder"

**Comment by MegaNarwhal** [comment]
This should be fixed in 1.3.1.
